/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_namaramoses_opencvprjct_Main2Activity */

#ifndef _Included_com_example_namaramoses_opencvprjct_Main2Activity
#define _Included_com_example_namaramoses_opencvprjct_Main2Activity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_RGBA
#define com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_RGBA 0L
#undef com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_GRAY
#define com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_GRAY 1L
#undef com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_CANNY
#define com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_CANNY 2L
#undef com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_FEATURES
#define com_example_namaramoses_opencvprjct_Main2Activity_VIEW_MODE_FEATURES 5L
/*
 * Class:     com_example_namaramoses_opencvprjct_Main2Activity
 * Method:    FindFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_namaramoses_opencvprjct_Main2Activity_FindFeatures
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
