/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_namaramoses_opencvprjct_Main2Activity */

#ifndef _Included_com_example_namaramoses_opencvprjct_Main2Activity
#define _Included_com_example_namaramoses_opencvprjct_Main2Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_namaramoses_opencvprjct_Main2Activity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */

#ifdef __cplusplus
}
#endif
#endif
